// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2hMqcA9V5eQAcgdTSPs5VlqncCtK-M5s',
    appId: '1:438191971847:web:1fc22dd012065eca7754a2',
    messagingSenderId: '438191971847',
    projectId: 'tarefacil-c0290',
    authDomain: 'tarefacil-c0290.firebaseapp.com',
    storageBucket: 'tarefacil-c0290.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArBmm_n065Vt420iQQ0F_aem1MwVwB2L4',
    appId: '1:438191971847:android:8b6556a83e0ac3587754a2',
    messagingSenderId: '438191971847',
    projectId: 'tarefacil-c0290',
    storageBucket: 'tarefacil-c0290.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Wh-HhWngFdFqB3eQHcv7AK-e_H9VpNk',
    appId: '1:438191971847:ios:0e6f6f09bc9774c17754a2',
    messagingSenderId: '438191971847',
    projectId: 'tarefacil-c0290',
    storageBucket: 'tarefacil-c0290.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2Wh-HhWngFdFqB3eQHcv7AK-e_H9VpNk',
    appId: '1:438191971847:ios:fcb730e99fa48e5c7754a2',
    messagingSenderId: '438191971847',
    projectId: 'tarefacil-c0290',
    storageBucket: 'tarefacil-c0290.appspot.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
